// AUTO-GENERATED by `zig build gen-client-ts`. DO NOT EDIT.
// Source of truth: src/binary_protocol.zig + src/schema.zig.
// Regenerate after any change to the Op enum, Status/SubStatus,
// or Category/Link extern struct layouts.

import { BufferReader } from "./buffer.ts";

export const enum Op {
  CreateLink = 1,
  CreateCategory = 2,
  GetLink = 3,
  GetCategory = 4,
  DeleteLink = 5,
  DeleteCategory = 6,
  UpdateCategory = 7,
  MoveCategory = 8,
  UpdateLink = 9,
  ListRootCategories = 10,
  BrowsePath = 11,
  ListChildren = 12,
  ListLinks = 13,
  Search = 14,
  Stats = 15,
  ListAllLinks = 16,
  ListSubtreeLinks = 17,
  IndexHealth = 18,
  RunVerifier = 19,
  RebuildIndex = 20,
  Snapshot = 22,
  OpLatencyStats = 23,
  BulkImport = 24,
  CreateSubmission = 25,
  UpdateLinkStatus = 26,
  ListLinksBySubmitter = 27,
  MoveLink = 28,
  GetCategoriesByIds = 29,
  BulkUpdateLinkStatus = 34,
  BulkDeleteLinks = 35,
  CountsByStatus = 36,
  Ping = 255,
}

export const enum Status {
  Ok = 0,
  NotFound = 1,
  Duplicate = 2,
  Invalid = 3,
  Err = 4,
  CategoryNotFound = 5,
  HasChildren = 6,
  Circular = 7,
}

export const enum SubStatus {
  None = 0,
  FieldTooLong = 1,
  InvalidSlug = 2,
  BufferTooSmall = 3,
  PathTooDeep = 4,
  UnsupportedOrder = 5,
  ParentNotFound = 6,
  DuplicateUrl = 7,
  OffsetTooLarge = 8,
  AlreadyInProgress = 9,
}

export const STATUS_MSG: Record<number, string> = {
  0: "ok",
  1: "not found",
  2: "duplicate",
  3: "invalid",
  4: "err",
  5: "category not found",
  6: "has children",
  7: "circular",
};

export const SUB_STATUS_MSG: Record<number, string> = {
  0: "none",
  1: "field too long",
  2: "invalid slug",
  3: "buffer too small",
  4: "path too deep",
  5: "unsupported order",
  6: "parent not found",
  7: "duplicate url",
  8: "offset too large",
  9: "already in progress",
};

export const CATEGORY_SIZE = 1288;
export const LINK_SIZE = 1888;

export type LinkStatus = "pending" | "approved" | "rejected" | "unknown";

export function linkStatusFromByte(b: number): LinkStatus {
  if (b === 0) return "pending";
  if (b === 1) return "approved";
  if (b === 2) return "rejected";
  return "unknown";
}

export function statusToCode(s: LinkStatus): number {
  if (s === "pending") return 0;
  if (s === "approved") return 1;
  if (s === "rejected") return 2;
  throw new Error(`statusToCode: cannot encode "${s}"`);
}

export interface Category {
  id: number;
  parentId: number;
  name: string;
  slug: string;
  description: string;
  linkCount: number;
  childCount: number;
  sortOrder: number;
  createdAt: Date;
  updatedAt: Date;
  linkCountSubtree: number;
  childCountSubtree: number;
  flags: number;
}

export interface Link {
  id: number;
  categoryId: number;
  url: string;
  title: string;
  description: string;
  sortOrder: number;
  createdAt: Date;
  updatedAt: Date;
  status: LinkStatus;
  submitterId: number;
  editorNote: string;
  tags: string;
  language: string;
  region: string;
  license: string;
}

export function readCategory(r: BufferReader): Category {
  const id = r.u64();
  const parentId = r.u64();
  const name = r.fixedString(64);
  const slug = r.fixedString(128);
  const description = r.fixedString(1024);
  r.skip(2); // alignment gap before link_count
  const linkCount = r.u32();
  const childCount = r.u32();
  const sortOrder = r.u32();
  r.skip(4); // _pad0
  const createdAt = r.timestamp();
  const updatedAt = r.timestamp();
  const linkCountSubtree = r.u64();
  const childCountSubtree = r.u32();
  const flags = r.u32();
  return {
    id,
    parentId,
    name,
    slug,
    description,
    linkCount,
    childCount,
    sortOrder,
    createdAt,
    updatedAt,
    linkCountSubtree,
    childCountSubtree,
    flags,
  };
}

export function readLink(r: BufferReader): Link {
  const id = r.u64();
  const categoryId = r.u64();
  const url = r.fixedString(64);
  const title = r.fixedString(128);
  const description = r.fixedString(256);
  r.skip(2); // alignment gap before sort_order
  const sortOrder = r.u32();
  r.skip(4); // _pad0
  const createdAt = r.timestamp();
  const updatedAt = r.timestamp();
  const status = linkStatusFromByte(r.u8());
  r.skip(7); // _pad1
  const submitterId = r.u64();
  const editorNote = r.fixedString(1024);
  const tags = r.fixedString(256);
  const language = r.fixedString(8);
  const region = r.fixedString(8);
  const license = r.fixedString(64);
  r.skip(6); // _pad2
  return {
    id,
    categoryId,
    url,
    title,
    description,
    sortOrder,
    createdAt,
    updatedAt,
    status,
    submitterId,
    editorNote,
    tags,
    language,
    region,
    license,
  };
}
