apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - statefulset.yaml
  - denokv.yaml
  - web.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml

namespace: dmozdb
