apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dmozdb
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - directory.junaid.guru
  rules:
    - host: directory.junaid.guru
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: web
                port:
                  number: 8000
