const std = @import("std");
const zigstore = @import("zigstore");
const tsgen = zigstore.tsgen;
const protocol = @import("binary_protocol.zig");
const schema = @import("schema.zig");

const FixedStringMeta = struct { capacity: usize };

const FieldTable = struct {
    pub fn tsType(comptime T: type, comptime field_name: []const u8) []const u8 {
        if (comptime isFixedString(T)) |_| return "string";
        if (comptime std.mem.eql(u8, field_name, "created_at") or std.mem.eql(u8, field_name, "updated_at")) return "Date";
        if (T == u8 and comptime std.mem.eql(u8, field_name, "status")) return "LinkStatus";
        return "number";
    }

    pub fn reader(comptime T: type, comptime field_name: []const u8) []const u8 {
        if (comptime isFixedString(T)) |fs| {
            return std.fmt.comptimePrint("r.fixedString({d})", .{fs.capacity});
        }
        if (T == u8) {
            if (comptime std.mem.eql(u8, field_name, "status")) return "linkStatusFromByte(r.u8())";
            return "r.u8()";
        }
        if (T == u16) return "r.u16()";
        if (T == u32) return "r.u32()";
        if (T == u64) return "r.u64()";
        if (T == i64) {
            if (comptime std.mem.eql(u8, field_name, "created_at") or std.mem.eql(u8, field_name, "updated_at")) {
                return "r.timestamp()";
            }
            return "r.i64()";
        }
        @compileError("FieldTable.reader: unsupported field type " ++ @typeName(T) ++ " for field " ++ field_name);
    }
};

fn isFixedString(comptime T: type) ?FixedStringMeta {
    const info = @typeInfo(T);
    if (info != .@"struct" or info.@"struct".layout != .@"extern") return null;
    const fields = info.@"struct".fields;
    if (fields.len != 2) return null;
    if (!std.mem.eql(u8, fields[0].name, "data")) return null;
    if (!std.mem.eql(u8, fields[1].name, "len")) return null;
    if (fields[1].type != u16) return null;
    const data_info = @typeInfo(fields[0].type);
    if (data_info != .array) return null;
    if (data_info.array.child != u8) return null;
    return .{ .capacity = data_info.array.len };
}

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var args = try std.process.argsWithAllocator(allocator);
    defer args.deinit();
    _ = args.next();
    const out_path = args.next() orelse "web/lib/dmoz-protocol.gen.ts";

    var file = try std.fs.cwd().createFile(out_path, .{ .truncate = true });
    defer file.close();

    var buf: [16384]u8 = undefined;
    var fw = file.writer(&buf);
    const w = &fw.interface;

    try writeHeader(w);
    try tsgen.writeOpEnum(w, "Op", protocol.Op);
    try tsgen.writeStatusEnum(w, "Status", protocol.Status);
    try tsgen.writeStatusEnum(w, "SubStatus", protocol.SubStatus);
    try tsgen.writeStatusMap(w, "STATUS_MSG", protocol.Status);
    try tsgen.writeStatusMap(w, "SUB_STATUS_MSG", protocol.SubStatus);
    try writeStructSize(w, "CATEGORY_SIZE", schema.Category);
    try writeStructSize(w, "LINK_SIZE", schema.Link);
    try writeLinkStatusEnum(w);
    try tsgen.writeStructInterface(w, FieldTable, "Category", schema.Category);
    try tsgen.writeStructInterface(w, FieldTable, "Link", schema.Link);
    try tsgen.writeStructReader(w, FieldTable, "Category", schema.Category);
    try tsgen.writeStructReader(w, FieldTable, "Link", schema.Link);
    try w.flush();
}

fn writeHeader(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\// AUTO-GENERATED by `zig build gen-client-ts`. DO NOT EDIT.
        \\// Source of truth: src/binary_protocol.zig + src/schema.zig.
        \\// Regenerate after any change to the Op enum, Status/SubStatus,
        \\// or Category/Link extern struct layouts.
        \\
        \\import { BufferReader } from "./buffer.ts";
        \\
        \\
    );
}

fn writeStructSize(w: *std.Io.Writer, comptime name: []const u8, comptime T: type) !void {
    try w.print("export const {s} = {d};\n", .{ name, @sizeOf(T) });
}

fn writeLinkStatusEnum(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\
        \\export type LinkStatus = "pending" | "approved" | "rejected" | "unknown";
        \\
        \\export function linkStatusFromByte(b: number): LinkStatus {
        \\
    );
    inline for (@typeInfo(schema.LinkStatus).@"enum".fields) |f| {
        try w.print("    if (b === {d}) return \"{s}\";\n", .{ f.value, f.name });
    }
    try w.writeAll(
        \\    return "unknown";
        \\}
        \\
        \\export function statusToCode(s: LinkStatus): number {
        \\
    );
    inline for (@typeInfo(schema.LinkStatus).@"enum".fields) |f| {
        try w.print("    if (s === \"{s}\") return {d};\n", .{ f.name, f.value });
    }
    try w.writeAll(
        \\    throw new Error(`statusToCode: cannot encode "${s}"`);
        \\}
        \\
        \\
    );
}
