const std = @import("std");
const protocol = @import("binary_protocol.zig");
const schema = @import("schema.zig");
const FixedStringMeta = struct { capacity: usize };

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var args = try std.process.argsWithAllocator(allocator);
    defer args.deinit();
    _ = args.next();
    const out_path = args.next() orelse "web/lib/dmoz-protocol.gen.ts";

    var file = try std.fs.cwd().createFile(out_path, .{ .truncate = true });
    defer file.close();

    var buf: [16384]u8 = undefined;
    var fw = file.writer(&buf);
    const w = &fw.interface;

    try writeHeader(w);
    try writeOpEnum(w);
    try writeStatusEnum(w, "Status", protocol.Status);
    try writeStatusEnum(w, "SubStatus", protocol.SubStatus);
    try writeStatusMap(w, "STATUS_MSG", protocol.Status);
    try writeStatusMap(w, "SUB_STATUS_MSG", protocol.SubStatus);
    try writeStructSize(w, "CATEGORY_SIZE", schema.Category);
    try writeStructSize(w, "LINK_SIZE", schema.Link);
    try writeLinkStatusEnum(w);
    try writeStructInterface(w, "Category", schema.Category);
    try writeStructInterface(w, "Link", schema.Link);
    try writeStructReader(w, "Category", schema.Category);
    try writeStructReader(w, "Link", schema.Link);
    try writeFooter(w);
    try w.flush();
}

fn writeHeader(w: anytype) !void {
    try w.writeAll(
        \\// AUTO-GENERATED by `zig build gen-client-ts`. DO NOT EDIT.
        \\// Source of truth: src/binary_protocol.zig + src/types.zig.
        \\// Regenerate after any change to the Op enum, Status/SubStatus,
        \\// or Category/Link extern struct layouts.
        \\
        \\import { BufferReader } from "./buffer.ts";
        \\
        \\
    );
}

fn writeFooter(w: anytype) !void {
    _ = w;
}

fn writeOpEnum(w: anytype) !void {
    try w.writeAll("export const enum Op {\n");
    inline for (@typeInfo(protocol.Op).@"enum".fields) |f| {
        const pascal = comptime snakeToPascal(f.name);
        try w.print("    {s} = {d},\n", .{ pascal, f.value });
    }
    try w.writeAll("}\n\n");
}

fn writeStatusEnum(w: anytype, comptime name: []const u8, comptime E: type) !void {
    try w.print("export const enum {s} {{\n", .{name});
    inline for (@typeInfo(E).@"enum".fields) |f| {
        const pascal = comptime snakeToPascal(f.name);
        try w.print("    {s} = {d},\n", .{ pascal, f.value });
    }
    try w.writeAll("}\n\n");
}

fn writeStatusMap(w: anytype, comptime name: []const u8, comptime E: type) !void {
    try w.print("export const {s}: Record<number, string> = {{\n", .{name});
    inline for (@typeInfo(E).@"enum".fields) |f| {
        const human = comptime snakeToHuman(f.name);
        try w.print("    {d}: \"{s}\",\n", .{ f.value, human });
    }
    try w.writeAll("};\n\n");
}

fn writeStructSize(w: anytype, comptime name: []const u8, comptime T: type) !void {
    try w.print("export const {s} = {d};\n", .{ name, @sizeOf(T) });
}

fn writeLinkStatusEnum(w: anytype) !void {
    try w.writeAll(
        \\
        \\export type LinkStatus = "pending" | "approved" | "rejected" | "unknown";
        \\
        \\export function linkStatusFromByte(b: number): LinkStatus {
        \\
    );
    inline for (@typeInfo(schema.LinkStatus).@"enum".fields) |f| {
        try w.print("    if (b === {d}) return \"{s}\";\n", .{ f.value, f.name });
    }
    try w.writeAll(
        \\    return "unknown";
        \\}
        \\
        \\export function statusToCode(s: LinkStatus): number {
        \\
    );
    inline for (@typeInfo(schema.LinkStatus).@"enum".fields) |f| {
        try w.print("    if (s === \"{s}\") return {d};\n", .{ f.name, f.value });
    }
    try w.writeAll(
        \\    throw new Error(`statusToCode: cannot encode "${s}"`);
        \\}
        \\
        \\
    );
}

fn isFixedString(comptime T: type) ?FixedStringMeta {
    const info = @typeInfo(T);
    if (info != .@"struct" or info.@"struct".layout != .@"extern") return null;
    const fields = info.@"struct".fields;
    if (fields.len != 2) return null;
    if (!std.mem.eql(u8, fields[0].name, "data")) return null;
    if (!std.mem.eql(u8, fields[1].name, "len")) return null;
    if (fields[1].type != u16) return null;
    const data_info = @typeInfo(fields[0].type);
    if (data_info != .array) return null;
    if (data_info.array.child != u8) return null;
    return .{ .capacity = data_info.array.len };
}

fn fieldTsType(comptime T: type, comptime field_name: []const u8) []const u8 {
    if (comptime isFixedString(T)) |_| return "string";
    if (comptime std.mem.eql(u8, field_name, "created_at") or std.mem.eql(u8, field_name, "updated_at")) return "Date";
    if (T == u8 and comptime std.mem.eql(u8, field_name, "status")) return "LinkStatus";
    return "number";
}

fn writeStructInterface(w: anytype, comptime name: []const u8, comptime T: type) !void {
    try w.print("export interface {s} {{\n", .{name});
    inline for (@typeInfo(T).@"struct".fields) |f| {
        if (comptime std.mem.startsWith(u8, f.name, "_pad")) continue;
        const camel = comptime fieldNameToCamel(f.name);
        const ts_type = comptime fieldTsType(f.type, f.name);
        try w.print("    {s}: {s};\n", .{ camel, ts_type });
    }
    try w.writeAll("}\n\n");
}

fn writeStructReader(w: anytype, comptime name: []const u8, comptime T: type) !void {
    try w.print("export function read{s}(r: BufferReader): {s} {{\n", .{ name, name });
    var cursor: usize = 0;
    inline for (@typeInfo(T).@"struct".fields) |f| {
        const target = @offsetOf(T, f.name);
        if (target > cursor) {
            try w.print("    r.skip({d}); // alignment gap before {s}\n", .{ target - cursor, f.name });
            cursor = target;
        }
        if (comptime std.mem.startsWith(u8, f.name, "_pad")) {
            try w.print("    r.skip({d}); // {s}\n", .{ @sizeOf(f.type), f.name });
            cursor += @sizeOf(f.type);
            continue;
        }
        if (comptime isFixedString(f.type)) |fs| {
            try w.print(
                "    const {s} = r.fixedString({d});\n",
                .{ fieldNameToCamel(f.name), fs.capacity },
            );
            cursor += @sizeOf(f.type);
            continue;
        }
        const reader = comptime primitiveReader(f.type, f.name);
        try w.print(
            "    const {s} = {s};\n",
            .{ fieldNameToCamel(f.name), reader },
        );
        cursor += @sizeOf(f.type);
    }
    if (cursor < @sizeOf(T)) {
        try w.print("    r.skip({d}); // tail padding to @sizeOf({s})\n", .{ @sizeOf(T) - cursor, name });
    }
    try w.writeAll("    return {\n");
    inline for (@typeInfo(T).@"struct".fields) |f| {
        if (comptime std.mem.startsWith(u8, f.name, "_pad")) continue;
        const camel = comptime fieldNameToCamel(f.name);
        try w.print("        {s},\n", .{camel});
    }
    try w.writeAll("    };\n");
    try w.writeAll("}\n\n");
}

fn primitiveReader(comptime T: type, comptime field_name: []const u8) []const u8 {
    if (T == u8) {
        if (comptime std.mem.eql(u8, field_name, "status")) return "linkStatusFromByte(r.u8())";
        return "r.u8()";
    }
    if (T == u16) return "r.u16()";
    if (T == u32) return "r.u32()";
    if (T == u64) return "r.u64()";
    if (T == i64) {
        if (comptime std.mem.eql(u8, field_name, "created_at") or std.mem.eql(u8, field_name, "updated_at")) {
            return "r.timestamp()";
        }
        return "r.i64()";
    }
    @compileError("primitiveReader: unsupported field type " ++ @typeName(T) ++ " for field " ++ field_name);
}

fn snakeToPascal(comptime s: []const u8) []const u8 {
    @setEvalBranchQuota(10000);
    const result = comptime blk: {
        var out: [s.len]u8 = undefined;
        var oi: usize = 0;
        var capitalise_next = true;
        for (s) |c| {
            if (c == '_') {
                capitalise_next = true;
                continue;
            }
            if (capitalise_next and c >= 'a' and c <= 'z') {
                out[oi] = c - ('a' - 'A');
            } else {
                out[oi] = c;
            }
            oi += 1;
            capitalise_next = false;
        }
        const f: [oi]u8 = out[0..oi].*;
        break :blk f;
    };
    return &result;
}

fn fieldNameToCamel(comptime s: []const u8) []const u8 {
    @setEvalBranchQuota(10000);
    const result = comptime blk: {
        var out: [s.len]u8 = undefined;
        var oi: usize = 0;
        var capitalise_next = false;
        for (s) |c| {
            if (c == '_') {
                capitalise_next = true;
                continue;
            }
            if (capitalise_next and c >= 'a' and c <= 'z') {
                out[oi] = c - ('a' - 'A');
            } else {
                out[oi] = c;
            }
            oi += 1;
            capitalise_next = false;
        }
        const f: [oi]u8 = out[0..oi].*;
        break :blk f;
    };
    return &result;
}

fn snakeToHuman(comptime s: []const u8) []const u8 {
    @setEvalBranchQuota(10000);
    const result = comptime blk: {
        var out: [s.len]u8 = undefined;
        for (s, 0..) |c, i| {
            out[i] = if (c == '_') ' ' else c;
        }
        const f: [s.len]u8 = out;
        break :blk f;
    };
    return &result;
}
